---
title: 'Class 12: web scraping + structured text extraction'
author: "Nathan Federer"
date: "2026-10-05"
output: 
  html_document:
  toc: true
  toc_float: true
  number_sections: true
  code_download: true
  code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## continuing with the plane crash info example 

```{r crashes}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

# How many <table> elements are on the page?
crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

# From a cleaning perspective: 
# [1] Obviously, translate this into a DF instead of a list
# [2] To replace the current headers with row 1 and then delete row 1
# [3] Convert Date into a date column instead of chr
# [4] More complex cleaning to split multiple information within a cell into seperate columns
# (outside of the scope of todays class -- feel fre to try Ai or regular questions if you are in 414)

#back to our pepper shaker analogy
crash_df = crash_tables[[1]] #subsetting a list

colnames(crash_df) = crash_df[1,]
crash_df = crash_df[-1,]

# to convert data column into a date type obj
crash_df = crash_df |> 
  dplyr::mutate(Date = lubridate::dmy(Date))

dplyr::glimpse(crash_df)
``` 


# Game
```{r game}
page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements(".Dreadnought") |>
  rvest::html_text2()
length(classes)   # check this first: one per card



base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351, by = 50)
pages = vector("list", length(starts)) #initializing the list [similar to initializing the df]
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |>
      rvest::html_text2(),
    value = pg |> rvest::html_elements("div > ul > li:nth-child(1) > span") |>
      rvest::html_text2() |> readr::parse_number()
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?

dreadnought_df = registry |>
  dplyr::filter(class == "Dreadnought")

sum(dreadnought_df$value)

```

## ISA 125 Extraction
```{r}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna"
)

isa125_courseblock = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements("#sc_sccoursedescs > div:nth-child(1)") |>
  rvest::html_text2()

chat$chat_structured(
  isa125_courseblock,
  type = ellmer::type_object(
    #Code is the name of the first element in the returned sublist
    #type_string -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number. For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(description = "The number of credits shown in paranthesis after the course code and title")
  )
)
```

## All 50 ISA courses
```{r all_isa_courses}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna"
)
course_vec = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |>
  rvest::html_elements(".courseblock") |> rvest::html_text2()

#similar to example
course_list = as.list(course_vec) # make it a list

# Fadel was lazy here and copied the schema from the prior example we did in class and now we apply it to all 50
type_course = ellmer::type_object(
    #Code is the name of the first element in the returned sublist
    #type_string -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number. For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(description = "The number of credits shown in paranthesis after the course code and title")
  )

isa_df = ellmer::parallel_chat_structured(
  chat, prompts = course_list, type = type_course,
  include_tokens = T, include_cost = T
)

sum(isa_df$cost)
```




